// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EscapeController from "./escape_controller"
application.register("escape", EscapeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NewPlayerNamesController from "./new_player_names_controller"
application.register("new-player-names", NewPlayerNamesController)

import PlayersFilenameController from "./players_filename_controller"
application.register("players-filename", PlayersFilenameController)
