// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AndroidButtonController from "./android_button_controller"
application.register("android-button", AndroidButtonController)

import DatatableController from "./datatable_controller"
application.register("datatable", DatatableController)

import EscapeController from "./escape_controller"
application.register("escape", EscapeController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FullscreenController from "./fullscreen_controller"
application.register("fullscreen", FullscreenController)

import GmapController from "./gmap_controller"
application.register("gmap", GmapController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NewPlayerNamesController from "./new_player_names_controller"
application.register("new-player-names", NewPlayerNamesController)

import OtherFieldController from "./other_field_controller"
application.register("other-field", OtherFieldController)

import PlayersFilenameController from "./players_filename_controller"
application.register("players-filename", PlayersFilenameController)

import RoundFinishedController from "./round_finished_controller"
application.register("round-finished", RoundFinishedController)

import ScoreboardController from "./scoreboard_controller"
application.register("scoreboard", ScoreboardController)

import SimulResultController from "./simul_result_controller"
application.register("simul-result", SimulResultController)

import SimulScoreController from "./simul_score_controller"
application.register("simul-score", SimulScoreController)

import ToggleInputController from "./toggle_input_controller"
application.register("toggle-input", ToggleInputController)
